version: "3.9"

services:
  java_app:
    container_name: obsac_app
    image: obsac:1.0
    build: .
    ports:
      - 8081:8080
    depends_on:
      - java_db
  java_db:
    container_name: obsac_db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres